### PR TITLE
Fix/endpoint calc cleanup

### LINKED ISSUE #14: [Info APi] Refactor modules and double-check all endpoints
1. New DPOS module that will be used both the nodes and the staking module.
2. Double check all endpoints and do the calculations manually. There might be something wrong there. Ex: https://github.com/Taraxa-project/tara-erc20-info-api/blob/main/src/node/node.service.ts#L84

### PR DESCRIPTION
**Pull request by VargaElod23**
- [x] Decommission `cumulativeCommission` endpoint until subgraph is done.
- [x] implements `cumulativeRewards` endpoint.
- [x] Fix contributions endpoint.
- [x] Correct avgStakingYield calculation.
- [x] Switch to 1 min cache for prices, use cacheManager.
- [x] Unify returns as strings.
- [x] Avoid floating point rounding after the 52nd bit.

### CODE REVIEW

File: src/node/node.controller.ts [hunk 1]
```diff
@@ -7,23 +7,31 @@ import {
 } from '@nestjs/common';
 import { ApiTags } from '@nestjs/swagger';
 import { NodeService } from './node.service';
+import { StakingService } from 'src/staking/staking.service';
+import { TokenService } from 'src/token/token.service';
```
Comment (rattrap) [inline src/node/node.controller.ts]: Absolute imports.

**Review by rattrap — CHANGES_REQUESTED** [review]

File: src/node/node.controller.ts [hunk 2]
```diff
@@ -57,6 +67,22 @@ export class NodeController {
...
+
+  /**
+   * Returns the cumulative rewards earned by Taraxa Validators on the Taraxa Mainnet
+   * @returns cumulative rewards in ETH
+   */
+  @Get('cumulativeRewards')
+  @CacheTTL(36000000)
+  @UseInterceptors(CacheInterceptor)
+  async cumulativeRewards() {
+    const INITIAL_SUPPLY = '10119799574107498232500000000';
```
Comment (rattrap) [inline src/node/node.controller.ts]: This should be 10bn

**Review by rattrap — CHANGES_REQUESTED** [review]

File: src/node/node.module.ts [hunk 3]
```diff
@@ -1,13 +1,15 @@
 import { HttpModule } from '@nestjs/axios';
 import { Module, CacheModule } from '@nestjs/common';
-import { BlockchainModule } from 'src/blockchain/blockchain.module';
 import { ConfigModule, ConfigService } from '@nestjs/config';
 import { NodeController } from './node.controller';
 import { NodeService } from './node.service';
 import { buildCacheConfig } from 'src/config/cacheConfig';
+import { StakingModule } from 'src/staking/staking.module';
+import { TokenModule } from 'src/token/token.module';
```
Comment (rattrap) [inline src/node/node.module.ts]: Relative imports.

Comment (rattrap) [reply src/node/node.module.ts]: + where do we use the Staking module?

File: src/token/token.service.ts [hunk 4]
```diff
@@ -13,6 +13,7 @@ import { HttpService } from '@nestjs/axios';
 import { firstValueFrom, catchError, map } from 'rxjs';
 import { Cache } from 'cache-manager';
 import { MarketDetails } from '../utils/types';
+import { StakingService } from 'src/staking/staking.service';
```
Comment (rattrap) [inline src/token/token.service.ts]: Relative imports

File: src/token/token.module.ts [hunk 5]
```diff
@@ -5,12 +5,14 @@ import { ConfigModule, ConfigService } from '@nestjs/config';
 import { TokenController } from './token.controller';
 import { TokenService } from './token.service';
 import { buildCacheConfig } from 'src/config/cacheConfig';
+import { StakingModule } from 'src/staking/staking.module';
```
Comment (rattrap) [inline src/token/token.module.ts]: Relative imports

File: src/token/token.service.ts [hunk 6]
```diff
@@ -138,12 +146,12 @@ export class TokenService {
...
     return (
-      (Number(await this.dposBalance()) /
+      (Number(await this.delegationService.totalDelegated()) /
         (Number(await this.totalSupply()) - Number(await this.totalLocked()))) *
       100
-    );
+    ).toString();
   }
-  async marketDetails() {
+  async marketDetails(asString?: boolean) {
```
Comment (rattrap) [inline src/token/token.service.ts]: This flag shouldn't be here. It will break the cached version 'cause you are not taking that into account

File: src/token/token.service.ts [hunk 7]
```diff
@@ -40,6 +42,11 @@ export class TokenService {
     return '18';
   }
   async getPrice() {
+    const key = this.redisName ? `${this.redisName}_marketCap` : 'marketCap';
```
Comment (rattrap) [inline src/token/token.service.ts]: It's weird 'cause you set this from another function that also calls this method 🤯

**Review by rattrap — CHANGES_REQUESTED** [review]

File: src/token/token.service.ts (hunk 7 above)
Comment (VargaElod23) [reply src/token/token.service.ts]: Right, I can reroute the controller call to the `marketDetails` and use this as internal
